print("Welcome to the band name generator!")
city = input("What is the name of the city you grew up in?\n")
pet = input("What is the name of your favorite pet?\n")
random = input("Type in a random word\n")
print((f'Your band name could be: {random} {city} {pet}'))